//
//  TarotCardData.swift
//  LIFESPACE
//
//  Created by Mario Sbardella on 2025-11-14.
//

import Foundation

let tarotCards: [TarotCard] = [

    // MARK: - Major Arcana (0–21)
    TarotCard(name: "The Fool",        image: "tarot_fool",        meaning: "Folly, mania, extravagance, intoxication, delirium, frenzy, bewrayment. A new beginning."),
    TarotCard(name: "The Magician",    image: "tarot_magician",    meaning: "Skill, diplomacy, address, subtlety; sickness, pain, loss, disaster, snares of enemies; self-confidence, will; the Querent, if male."),
    TarotCard(name: "The High Priestess", image: "tarot_high_priestess", meaning: "Secrets, mystery, the future as yet unrevealed; the woman who interests the Querent, if male; the Querent herself, if female; silence, tenacity; mystery, wisdom, science."),
    TarotCard(name: "The Empress",     image: "tarot_empress",     meaning: "Fruitfulness, action, initiative, length of days; the unknown, clandestine; also difficulty, doubt, ignorance."),
    TarotCard(name: "The Emperor",     image: "tarot_emperor",     meaning: "Stability, power, protection, realization; a great person; aid, reason, conviction; authority and will."),
    TarotCard(name: "The Hierophant",  image: "tarot_hierophant",  meaning: "Marriage, alliance, captivity, servitude; mercy and goodness; inspiration; the man to whom the Querent has recourse."),
    TarotCard(name: "The Lovers",      image: "tarot_lovers",      meaning: "Attraction, love, beauty, trials overcome."),
    TarotCard(name: "The Chariot",     image: "tarot_chariot",     meaning: "Succour, providence; war, triumph, presumption, vengeance, trouble."),
    TarotCard(name: "Strength",        image: "tarot_strength",    meaning: "Power, energy, action, courage, magnanimity; complete success and honours."),
    TarotCard(name: "The Hermit",      image: "tarot_hermit",      meaning: "Prudence, circumspection; treason, dissimulation, roguery, corruption."),
    TarotCard(name: "Wheel of Fortune", image: "tarot_wheel_of_fortune", meaning: "Destiny, fortune, success, elevation, luck, felicity."),
    TarotCard(name: "Justice",         image: "tarot_justice",     meaning: "Equity, rightness, probity, executive; triumph of the deserving side in law."),
    TarotCard(name: "The Hanged Man",  image: "tarot_hanged_man",  meaning: "Wisdom, circumspection, discernment, trials, sacrifice, intuition, divination, prophecy."),
    TarotCard(name: "Death",           image: "tarot_death",       meaning: "End, mortality, destruction, corruption; for a man, loss of a benefactor; for a woman, contrarieties; for a maid, failed marriage projects."),
    TarotCard(name: "Temperance",      image: "tarot_temperance",  meaning: "Economy, moderation, frugality, management, accommodation."),
    TarotCard(name: "The Devil",       image: "tarot_devil",       meaning: "Ravage, violence, vehemence, extraordinary efforts, force, fatality; predestined forces not necessarily evil."),
    TarotCard(name: "The Tower",       image: "tarot_tower",       meaning: "Misery, distress, indigence, adversity, calamity, disgrace, deception, ruin; unforeseen catastrophe."),
    TarotCard(name: "The Star",        image: "tarot_star",        meaning: "Loss, theft, privation, abandonment; hope and bright prospects."),
    TarotCard(name: "The Moon",        image: "tarot_moon",        meaning: "Hidden enemies, danger, calumny, darkness, terror, deception, occult forces, error."),
    TarotCard(name: "The Sun",         image: "tarot_sun",         meaning: "Material happiness, fortunate marriage, contentment."),
    TarotCard(name: "The Last Judgement",       image: "tarot_judgement",   meaning: "Change of position, renewal, outcome; total loss through lawsuit."),
    TarotCard(name: "The World",       image: "tarot_world",       meaning: "Assured success, recompense, voyage, route, emigration, flight, change of place."),

    // MARK: - Wands (Fire)
    TarotCard(name: "Ace of Wands",        image: "tarot_wands_ace",        meaning: "Creation, invention, enterprise, beginning; birth, family, origin, and in a sense the virility which is behind them; the starting point of enterprises; according to another account, money, fortune, inheritance. Trickery. Small success. Favourable chance."),
    TarotCard(name: "Two of Wands",        image: "tarot_wands_2",          meaning: "Between the alternative readings there is no marriage possible; on the one hand, riches, fortune, magnificence; on the other, physical suffering, disease, chagrin, sadness, mortification. Accord, security, contention."),
    TarotCard(name: "Three of Wands",      image: "tarot_wands_3",          meaning: "He symbolizes established strength, enterprise, effort, trade, commerce, discovery; those are his ships, bearing his merchandise, which are sailing over the sea. The card also signifies able co-operation in business, as if the successful merchant prince were looking from his side towards yours with a view to help you. Calm, unity, progress."),
    TarotCard(name: "Four of Wands",       image: "tarot_wands_4",          meaning: "They are for once almost on the surface – country life, haven of refuge, a species of domestic harvest-home, repose, concord, harmony, prosperity, peace, and the perfected work of these. Insomnia, a subject of reflection, journey near at hand."),
    TarotCard(name: "Five of Wands",       image: "tarot_wands_5",          meaning: "Imitation, as, for example, sham fight, but also the strenuous competition and struggle of the search after riches and fortune. In this sense it connects with the battle of life. Hence some attributions say that it is a card of gold, gain, opulence. Vigils, determination, regularity."),
    TarotCard(name: "Six of Wands",        image: "tarot_wands_6",          meaning: "The card has been so designed that it can cover several significations; on the surface, it is a victor triumphing, but it is also great news, such as might be carried in state by the King's courier; it is expectation crowned with its own desire, the crown of hope, and so forth. Servants may lose the confidence of their masters; a young lady may be betrayed by a friend. Irritability, success, abundance."),
    TarotCard(name: "Seven of Wands",      image: "tarot_wands_7",          meaning: "It is a card of valour, for, on the surface, six are attacking one, who has, however, the vantage position. On the intellectual plane, it signifies discussion, wordy strife; in business – negotiations, war of trade, barter, competition. It is further a card of success, for the combatant is on the top and his enemies may be unable to reach him. News, infirmity, intrigue."),
    TarotCard(name: "Eight of Wands",      image: "tarot_wands_8",          meaning: "Swiftness, great haste, great hope, speed towards an end."),
    TarotCard(name: "Nine of Wands",       image: "tarot_wands_9",          meaning: "Strength in opposition, delay, suspension."),
    TarotCard(name: "Ten of Wands",        image: "tarot_wands_10",         meaning: "Oppression, lost lawsuits."),
    TarotCard(name: "Page of Wands",       image: "tarot_wands_page",       meaning: "Strange tidings, postman, messages."),
    TarotCard(name: "Knight of Wands",     image: "tarot_wands_knight",     meaning: "Flight, change of residence."),
    TarotCard(name: "Queen of Wands",      image: "tarot_wands_queen",      meaning: "Warmth, magnetic presence, love of money."),
    TarotCard(name: "King of Wands",       image: "tarot_wands_king",       meaning: "Friendly leader, warm, honest, conscientious."),

    // MARK: - Cups (Water)
    TarotCard(name: "Ace of Cups",         image: "tarot_cups_ace",         meaning: "True heart, joy, contentment, nourishment, abundance, fertility."),
    TarotCard(name: "Two of Cups",         image: "tarot_cups_2",           meaning: "Love, passion, friendship, affinity, union, sexual reltions, sanctification."),
    TarotCard(name: "Three of Cups",       image: "tarot_cups_3",           meaning: "The conclusion of any matter, happiness, victory, healing."),
    TarotCard(name: "Four of Cups",        image: "tarot_cups_4",           meaning: "Disgust, aversion, fairy gift offered but the Querent sees no consolation therein."),
    TarotCard(name: "Five of Cups",        image: "tarot_cups_5",           meaning: "Loss, inheritance, bitter or frustrating marriage."),
    TarotCard(name: "Six of Cups",         image: "tarot_cups_6",           meaning: "Nostalgia, memories. Alternatively, new relations, new environment and new knowledge."),
    TarotCard(name: "Seven of Cups",       image: "tarot_cups_7",           meaning: "Fairy favors, imagination, attainment but nothing permanent or substantial."),
    TarotCard(name: "Eight of Cups",       image: "tarot_cups_8",           meaning: "Deserting enterprise, undertaking or previous concern."),
    TarotCard(name: "Nine of Cups",        image: "tarot_cups_9",           meaning: "Contentment, success, advantage."),
    TarotCard(name: "Ten of Cups",         image: "tarot_cups_10",          meaning: "Contentment, the town, village or country inhabited by the Querent."),
    TarotCard(name: "Page of Cups",        image: "tarot_cups_page",        meaning: "Effeminate, impelled to render service, news, messages."),
    TarotCard(name: "Knight of Cups",      image: "tarot_cups_knight",      meaning: "Imagination, arrival, approach, advances, proposition, invitation."),
    TarotCard(name: "Queen of Cups",       image: "tarot_cups_queen",       meaning: "Good woman who will do service to the Querent, loving intelligence, pleasure, happiness."),
    TarotCard(name: "King of Cups",        image: "tarot_cups_king",        meaning: "Man of business or law, creative intelligence."),

    // MARK: - Swords (Air)
    TarotCard(name: "Ace of Swords",       image: "tarot_swords_ace",       meaning: "Triumph, conquest, great force in love as well as in hatred."),
    TarotCard(name: "Two of Swords",       image: "tarot_swords_2",         meaning: "Conformity, courage, friendship, intimacy."),
    TarotCard(name: "Three of Swords",     image: "tarot_swords_3",         meaning: "Absence, delay, division, rupture."),
    TarotCard(name: "Four of Swords",      image: "tarot_swords_4",         meaning: "Retreat, solitude, hermit's response, exile."),
    TarotCard(name: "Five of Swords",      image: "tarot_swords_5",         meaning: "Degradation, infamy, dishonor, loss."),
    TarotCard(name: "Six of Swords",       image: "tarot_swords_6",         meaning: "Transition, journey by the water"),
    TarotCard(name: "Seven of Swords",     image: "tarot_swords_7",         meaning: "Attempt, wish, hope, confidence, quarrelling, a plan that may fail, annoyance."),
    TarotCard(name: "Eight of Swords",     image: "tarot_swords_8",         meaning: "Bad news, crisis, sickness."),
    TarotCard(name: "Nine of Swords",      image: "tarot_swords_9",         meaning: "Death, failure, miscarriage, delay, deception, disappointment, despair."),
    TarotCard(name: "Ten of Swords",       image: "tarot_swords_10",        meaning: "Pain, affliction, tears, sadness, desolation."),
    TarotCard(name: "Page of Swords",      image: "tarot_swords_page",      meaning: "Authority, overseeing, spying."),
    TarotCard(name: "Knight of Swords",    image: "tarot_swords_knight",    meaning: "Skill, war, destruction, ruin."),
    TarotCard(name: "Queen of Swords",     image: "tarot_swords_queen",     meaning: "Widowhood, female sadness and embarassment, sterility, mourning."),
    TarotCard(name: "King of Swords",      image: "tarot_swords_king",      meaning: "Intellectual power, command, authority."),

    // MARK: - Pentacles (Earth)
    TarotCard(name: "Ace of Pentacles",    image: "tarot_pentacles_ace",    meaning: "Contentment, ecstasy, quick wit, gold."),
    TarotCard(name: "Two of Pentacles",    image: "tarot_pentacles_2",      meaning: "Gaiety, recreation, news and messages in writing such as obstacles or trouble."),
    TarotCard(name: "Three of Pentacles",  image: "tarot_pentacles_3",      meaning: "Trade, skilled labor, nobility, aristocracy, renown, glory."),
    TarotCard(name: "Four of Pentacles",   image: "tarot_pentacles_4",      meaning: "Cleaving to possessions, gifts, inheritance."),
    TarotCard(name: "Five of Pentacles",   image: "tarot_pentacles_5",      meaning: "Material trouble, love and lovers."),
    TarotCard(name: "Six of Pentacles",    image: "tarot_pentacles_6",      meaning: "Presents, gifts, gratification."),
    TarotCard(name: "Seven of Pentacles",  image: "tarot_pentacles_7",      meaning: "Money or business. Alternatively, quarrels or purgation."),
    TarotCard(name: "Eight of Pentacles",  image: "tarot_pentacles_8",      meaning: "Work, employment, commission, craftsmanship, skill in craft and business."),
    TarotCard(name: "Nine of Pentacles",   image: "tarot_pentacles_9",      meaning: "Safety, success, accomplishment, discernment."),
    TarotCard(name: "Ten of Pentacles",    image: "tarot_pentacles_10",     meaning: "Gain, riches, family matters."),
    TarotCard(name: "Page of Pentacles",   image: "tarot_pentacles_page",   meaning: "Study, scholarship, news."),
    TarotCard(name: "Knight of Pentacles", image: "tarot_pentacles_knight", meaning: "Hard work, routine, slow but reliable progress."),
    TarotCard(name: "Queen of Pentacles",  image: "tarot_pentacles_queen",  meaning: "Nurturing, opulence, generosity, security."),
    TarotCard(name: "King of Pentacles",   image: "tarot_pentacles_king",   meaning: "Wealth, successful business, normal intellectual aptitude."),

    // MARK: - Major Arcana (Reversed)
    TarotCard(name: "The Fool (Reversed)",        image: "tarot_fool_rev",        meaning: "Carelessness, apathy, vanity."),
    TarotCard(name: "The Magician (Reversed)",    image: "tarot_magician_rev",    meaning: "Mental illness, disgrace, disquiet."),
    TarotCard(name: "The High Priestess (Reversed)", image: "tarot_high_priestess_rev", meaning: "Moral or physical ardor, conceit, surface knowledge."),
    TarotCard(name: "The Empress (Reversed)",     image: "tarot_empress_rev",     meaning: "Light, truth, public rejoice."),
    TarotCard(name: "The Emperor (Reversed)",     image: "tarot_emperor_rev",     meaning: "Credit, immaturity, benevolence, compassion, confusion to enemies."),
    TarotCard(name: "The Hierophant (Reversed)",  image: "tarot_hierophant_rev",  meaning: "Overkindness, weakness, concord."),
    TarotCard(name: "The Lovers (Reversed)",      image: "tarot_lovers_rev",      meaning: "Disharmony, failure, foolish designs."),
    TarotCard(name: "The Chariot (Reversed)",     image: "tarot_chariot_rev",     meaning: "Riot, quarrel, dispute, litigation, defeat."),
    TarotCard(name: "Strength (Reversed)",        image: "tarot_strength_rev",    meaning: "Abuse of power, despotism, weakness."),
    TarotCard(name: "The Hermit (Reversed)",      image: "tarot_hermit_rev",      meaning: "Policy, fear, unreasoned caution."),
    TarotCard(name: "Wheel of Fortune (Reversed)", image: "tarot_wheel_of_fortune_rev", meaning: "Increase, abundance, superfluity."),
    TarotCard(name: "Justice (Reversed)",         image: "tarot_justice_rev",     meaning: "Bigotry, bias, excessive severity."),
    TarotCard(name: "The Hanged Man (Reversed)",  image: "tarot_hanged_man_rev",  meaning: "Selfishness, the crowd, body politic."),
    TarotCard(name: "Death (Reversed)",           image: "tarot_death_rev",       meaning: "Sleep, lethargy, somnambulism."),
    TarotCard(name: "Temperance (Reversed)",      image: "tarot_temperance_rev",  meaning: "Churches, religions, sects, the priesthood."),
    TarotCard(name: "The Devil (Reversed)",       image: "tarot_devil_rev",       meaning: "Evil fatality, weakness, pettiness."),
    TarotCard(name: "The Tower (Reversed)",       image: "tarot_tower_rev",       meaning: "Adversity, distress, indigence, disgrace."),
    TarotCard(name: "The Star (Reversed)",        image: "tarot_star_rev",        meaning: "Arrogance, impotence, haughtiness."),
    TarotCard(name: "The Moon (Reversed)",        image: "tarot_moon_rev",        meaning: "Confusion lifting, truths emerging, silence."),
    TarotCard(name: "The Sun (Reversed)",         image: "tarot_sun_rev",         meaning: "Material happiness, fortunate marriage, contentment."),
    TarotCard(name: "Judgement (Reversed)",       image: "tarot_judgement_rev",   meaning: "Deliberation, decision, sentence."),
    TarotCard(name: "The World (Reversed)",       image: "tarot_world_rev",       meaning: "Stagnation, inertia, fixity."),

    // MARK: - Wands (Reversed)
    TarotCard(name: "Ace of Wands (Reversed)",        image: "tarot_wands_ace_rev",        meaning: "Fall, decadence, ruin."),
    TarotCard(name: "Two of Wands (Reversed)",        image: "tarot_wands_2_rev",          meaning: "Surprise, wonder, enchantment, emotion, trouble, fear."),
    TarotCard(name: "Three of Wands (Reversed)",      image: "tarot_wands_3_rev",          meaning: "The end all troubles, adversity, dissapointment or toil."),
    TarotCard(name: "Four of Wands (Reversed)",       image: "tarot_wands_4_rev",          meaning: "Harmony, prosperity, peace."),
    TarotCard(name: "Five of Wands (Reversed)",       image: "tarot_wands_5_rev",          meaning: "Trickery, contradiction, litigation, disputes."),
    TarotCard(name: "Six of Wands (Reversed)",        image: "tarot_wands_6_rev",          meaning: "Apprehension, fear, gates being opened to the enemy."),
    TarotCard(name: "Seven of Wands (Reversed)",      image: "tarot_wands_7_rev",          meaning: "Perplexity, embarassment, anxiety."),
    TarotCard(name: "Eight of Wands (Reversed)",      image: "tarot_wands_8_rev",          meaning: "Jealousy, internal dispute, quarrels."),
    TarotCard(name: "Nine of Wands (Reversed)",       image: "tarot_wands_9_rev",          meaning: "Obstacles, adversity, calamity."),
    TarotCard(name: "Ten of Wands (Reversed)",        image: "tarot_wands_10_rev",         meaning: "Contrarieties, difficulties, intrigues."),
    TarotCard(name: "Page of Wands (Reversed)",       image: "tarot_wands_page_rev",       meaning: "Bad news, indecision, instability."),
    TarotCard(name: "Knight of Wands (Reversed)",     image: "tarot_wands_knight_rev",     meaning: "Division, interruption, discord."),
    TarotCard(name: "Queen of Wands (Reversed)",      image: "tarot_wands_queen_rev",      meaning: "Jealousy, deceit, infidelity."),
    TarotCard(name: "King of Wands (Reversed)",       image: "tarot_wands_king_rev",       meaning: "Tyrannical energy, impatience, domineering or arrogant leadership."),

    // MARK: - Cups (Reversed)
    TarotCard(name: "Ace of Cups (Reversed)",         image: "tarot_cups_ace_rev",         meaning: "False heart, mutation, instability."),
    TarotCard(name: "Two of Cups (Reversed)",         image: "tarot_cups_2_rev",           meaning: "False love, folly, misunderstanding."),
    TarotCard(name: "Three of Cups (Reversed)",       image: "tarot_cups_3_rev",           meaning: "Dispatch, achievement, end."),
    TarotCard(name: "Four of Cups (Reversed)",        image: "tarot_cups_4_rev",           meaning: "Novelty, omen, new instructions, new relations."),
    TarotCard(name: "Five of Cups (Reversed)",        image: "tarot_cups_5_rev",           meaning: "News, ancestry, return."),
    TarotCard(name: "Six of Cups (Reversed)",         image: "tarot_cups_6_rev",           meaning: "Renewal, the future, that which will come to pass."),
    TarotCard(name: "Seven of Cups (Reversed)",       image: "tarot_cups_7_rev",           meaning: "Desire, will, determination."),
    TarotCard(name: "Eight of Cups (Reversed)",       image: "tarot_cups_8_rev",           meaning: "Great joy, happiness, determination."),
    TarotCard(name: "Nine of Cups (Reversed)",        image: "tarot_cups_9_rev",           meaning: "Truth, loyalty, liberty."),
    TarotCard(name: "Ten of Cups (Reversed)",         image: "tarot_cups_10_rev",          meaning: "False heart, indignation, violence."),
    TarotCard(name: "Page of Cups (Reversed)",        image: "tarot_cups_page_rev",        meaning: "Attachment, seduction, deception."),
    TarotCard(name: "Knight of Cups (Reversed)",      image: "tarot_cups_knight_rev",      meaning: "Trickery, swindling, fraud."),
    TarotCard(name: "Queen of Cups (Reversed)",       image: "tarot_cups_queen_rev",       meaning: "Perverse woman, vice, dishonor, depravity."),
    TarotCard(name: "King of Cups (Reversed)",        image: "tarot_cups_king_rev",        meaning: "Dishonesty, double-dealing, vice."),

    // MARK: - Swords (Reversed)
    TarotCard(name: "Ace of Swords (Reversed)",       image: "tarot_swords_ace_rev",       meaning: "Great force of love or hate and the results are disastrous."),
    TarotCard(name: "Two of Swords (Reversed)",       image: "tarot_swords_2_rev",         meaning: "Falsehood, duplicity, disloyalty."),
    TarotCard(name: "Three of Swords (Reversed)",     image: "tarot_swords_3_rev",         meaning: "Error, loss, distraction, disorder, confusion."),
    TarotCard(name: "Four of Swords (Reversed)",      image: "tarot_swords_4_rev",         meaning: "Wise administration, government, economy, precaution."),
    TarotCard(name: "Five of Swords (Reversed)",      image: "tarot_swords_5_rev",         meaning: "Degradation, infamy, dishonor, loss."),
    TarotCard(name: "Six of Swords (Reversed)",       image: "tarot_swords_6_rev",         meaning: "Declaration, confession, publicity, and possibly a proposal of love."),
    TarotCard(name: "Seven of Swords (Reversed)",     image: "tarot_swords_7_rev",         meaning: "Good advice, slander, or babbling."),
    TarotCard(name: "Eight of Swords (Reversed)",     image: "tarot_swords_8_rev",         meaning: "Disquiet, difficulty, opposition, accident, treachery, the unforeseen, fatality."),
    TarotCard(name: "Nine of Swords (Reversed)",      image: "tarot_swords_9_rev",         meaning: "Imprisonment, doubt, suspicion, reasonable fear, shame."),
    TarotCard(name: "Ten of Swords (Reversed)",       image: "tarot_swords_10_rev",        meaning: "Advantage, profit, success, favor, power, authority, but none of these are permanent."),
    TarotCard(name: "Page of Swords (Reversed)",      image: "tarot_swords_page_rev",      meaning: "Gossip, spying with evil intentions, eavesdropping, sickness."),
    TarotCard(name: "Knight of Swords (Reversed)",    image: "tarot_swords_knight_rev",    meaning: "Folly, incapacity, extravagance."),
    TarotCard(name: "Queen of Swords (Reversed)",     image: "tarot_swords_queen_rev",     meaning: "Bigotry, prudery, deceit."),
    TarotCard(name: "King of Swords (Reversed)",      image: "tarot_swords_king_rev",      meaning: "Cruelty, evil intentions and malicious use of intellectual abilities."),

    // MARK: - Pentacles (Reversed)
    TarotCard(name: "Ace of Pentacles (Reversed)",    image: "tarot_pentacles_ace_rev",    meaning: "Greed, evil intelligence."),
    TarotCard(name: "Two of Pentacles (Reversed)",    image: "tarot_pentacles_2_rev",      meaning: "Fake positivity, simulated enjoyment, letters of exchange."),
    TarotCard(name: "Three of Pentacles (Reversed)",  image: "tarot_pentacles_3_rev",      meaning: "Mediocrity in work."),
    TarotCard(name: "Four of Pentacles (Reversed)",   image: "tarot_pentacles_4_rev",      meaning: "Suspense or delay."),
    TarotCard(name: "Five of Pentacles (Reversed)",   image: "tarot_pentacles_5_rev",      meaning: "Disorder, chaos, discord."),
    TarotCard(name: "Six of Pentacles (Reversed)",    image: "tarot_pentacles_6_rev",      meaning: "Desire, envy, illusion."),
    TarotCard(name: "Seven of Pentacles (Reversed)",  image: "tarot_pentacles_7_rev",      meaning: "Anxiety about money."),
    TarotCard(name: "Eight of Pentacles (Reversed)",  image: "tarot_pentacles_8_rev",      meaning: "Voided ambition, vanity, exaction."),
    TarotCard(name: "Nine of Pentacles (Reversed)",   image: "tarot_pentacles_9_rev",      meaning: "Roguery, deception, bad faith."),
    TarotCard(name: "Ten of Pentacles (Reversed)",    image: "tarot_pentacles_10_rev",     meaning: "Chance, fatality, loss, robbery, gambling, gifts, dowry, pension."),
    TarotCard(name: "Page of Pentacles (Reversed)",   image: "tarot_pentacles_page_rev",   meaning: "Prodigal son, liberal, luxury, bad news."),
    TarotCard(name: "Knight of Pentacles (Reversed)", image: "tarot_pentacles_knight_rev", meaning: "Inertia, idleness, stagnation."),
    TarotCard(name: "Queen of Pentacles (Reversed)",  image: "tarot_pentacles_queen_rev",  meaning: "Evil, fear, suspicion, suspense, mistrust."),
    TarotCard(name: "King of Pentacles (Reversed)",   image: "tarot_pentacles_king_rev",   meaning: "Vice, perversity, corruption, miser.")
]

